export const houses = [
  {
    id: crypto.randomUUID(),
    address: "N82 7328, Cantanhede, Lisboa",
    image: "house_1",
    crime_rating: 0,
    school_rating: 5,
    amenities: ["Swimming Pool"],
    transportations: ["Bus", "Subway", "Tricycle", "Grab"],
  },
  {
    id: crypto.randomUUID(),
    address: "N3 8781 Mealhada, Viseu",
    image: "house_1",
    crime_rating: 3,
    school_rating: 3,
    amenities: [],
    transportations: ["Tricycle", "Grab"],
  },
  {
    id: crypto.randomUUID(),
    address: "796 Waters Road Territoires du Nord-Ouest",
    image: "house_2",
    crime_rating: 1,
    school_rating: 0,
    amenities: ["Gym"],
    transportations: ["Subway", "Tricycle"],
  },
  {
    id: crypto.randomUUID(),
    address: "7098 Oberbrunner View, Runteton",
    image: "house_3",
    crime_rating: 0,
    school_rating: 5,
    amenities: ["Swimming Pool", "Gym"],
    transportations: ["Bus", "Subway", "Tricycle", "Grab"],
  },
  {
    id: crypto.randomUUID(),
    address: "717 Wunsch Manors, Gretchentown, Saskatchewan",
    image: "house_3",
    crime_rating: 5,
    school_rating: 3,
    amenities: ["Gym"],
    transportations: [],
  },
  {
    id: crypto.randomUUID(),
    address: "2669 Wiza Route, Yukon",
    image: "house_4",
    crime_rating: 0,
    school_rating: 4,
    amenities: ["Swimming Pool", "Gym"],
    transportations: ["Bus", "Subway", "Grab"],
  },
  {
    id: crypto.randomUUID(),
    address: "76062 Kohler Villages, Yukon",
    image: "house_1",
    crime_rating: 0,
    school_rating: 3,
    amenities: ["Swimming Pool", "Gym"],
    transportations: ["Tricycle"],
  },
  {
    id: crypto.randomUUID(),
    address: "7759 Helene Trafficway, Alberta",
    image: "house_5",
    crime_rating: 0,
    school_rating: 5,
    amenities: ["Swimming Pool", "Gym"],
    transportations: ["Subway", "Tricycle", "Grab"],
  },
  {
    id: crypto.randomUUID(),
    address: "05 Hessel Boulevard, New South Wales",
    image: "house_6",
    crime_rating: 1,
    school_rating: 5,
    amenities: ["Swimming Pool", "Gym"],
    transportations: ["Bus", , "Grab"],
  },
];
